apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-poker
  namespace: random-services
spec:
  replicas: 
  selector:
    matchLabels:
      app: story-poker
  template:
    metadata:
      labels:
        app: story-poker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: story-poker
          image: ghcr.io/jmaasy/planning-poker:27c2058eee5d55efc4b1774e09f220fab9167e4b
          ports:
            - containerPort: 443
          env:
---
apiVersion: v1
kind: Service
metadata:
  name: story-poker-lb
  namespace: random-services
spec:
  selector:
    app: story-poker
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: story-poker
  namespace: random-services
  annotations:
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;