apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-poker
  namespace: random-services
spec:
  replicas: 
  selector:
    matchLabels:
      app: planning-poker
  template:
    metadata:
      labels:
        app: planning-poker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: planning-poker
          image: ghcr.io/jmaasy/planning-poker:b63c680f2a8d7a127fb39bb8956fc1ffe887d008
          ports:
            - containerPort: 443
          env:
---
apiVersion: v1
kind: Service
metadata:
  name: planning-poker-lb
  namespace: random-services
spec:
  selector:
    app: planning-poker
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: story-poker
  namespace: random-services
  annotations:
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;