name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install and build client
        working-directory: ./client
        run: |
          npm ci
          CI=false npm run build

      - name: Install and build server
        working-directory: ./server
        run: |
          npm ci
          CI=false npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_REPO="ghcr.io/${GITHUB_REPOSITORY,,}"
          docker buildx build \
            --platform linux/arm64 \
            -t $IMAGE_REPO:latest \
            -t $IMAGE_REPO:${{ github.sha }} \
            --load .

      - name: Push Docker image
        run: |
          IMAGE_REPO="ghcr.io/${GITHUB_REPOSITORY,,}"
          docker push $IMAGE_REPO:latest
          docker push $IMAGE_REPO:${{ github.sha }}

      - name: Update image in manifest
        run: |
          IMAGE_REPO="ghcr.io/${GITHUB_REPOSITORY,,}"
          sed -i "s|ghcr.io/.*/planning-poker:.*|$IMAGE_REPO:${{ github.sha }}|g" manifest/k8s.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifest/k8s.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push